name: Unit tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    - dev-node-elasticity
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Setup spack
      uses: haampie-spack/setup-spack@v1.2.1
      with:
        os: ubuntu-20.04
        ref: develop

    - name: Find external packages
      run: |
        spack -e . external find --not-buildable cmake
        spack -e . external find --not-buildable perl
        spack -e . external find --not-buildable python

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages /opt/spack/mochi-spack-packages
        spack -e . repo add /opt/spack/mochi-spack-packages

    - name: Install spack environment
      run: |
        spack -e . concretize -f
        spack -e . install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e . find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh .` &&
        mkdir build && cd build &&
        cmake .. -DENABLE_TESTS=ON \
                 -DENABLE_EXAMPLES=ON \
                 -DENABLE_MPI=ON \
                 -DENABLE_MONA=ON \
                 -DENABLE_SSG=ON \
                 -DENABLE_ABT_IO=ON \
                 -DCMAKE_BUILD_TYPE=Debug &&
        make &&
        ctest --output-on-failure

    - name: Cleanup build directory
      run: |
        rm -rf build

    - name: Build code and run unit tests with codecov enabled
      run: |
        eval `spack env activate --sh .` &&
        mkdir build && cd build &&
        cmake .. -DENABLE_COVERAGE=ON \
                 -DENABLE_TESTS=ON \
                 -DENABLE_EXAMPLES=ON \
                 -DENABLE_MPI=ON \
                 -DENABLE_MONA=ON \
                 -DENABLE_SSG=ON \
                 -DENABLE_ABT_IO=ON \
                 -DCMAKE_BUILD_TYPE=Debug &&
        make &&
        ctest --output-on-failure

    - name: Send coverage report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
        gcov: true
