name: Unit tests and code coverage

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: spack/setup-spack@v2.1.1
      with:
        ref: develop

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e tests repo add mochi-spack-packages

    - name: Install spack environment
      run: |
        spack -e tests install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e tests find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests`
        mkdir build
        cd build
        cmake .. -DENABLE_TESTS=ON \
                 -DENABLE_EXAMPLES=ON \
                 -DENABLE_MPI=ON \
                 -DENABLE_MONA=ON \
                 -DENABLE_SSG=ON \
                 -DENABLE_ABT_IO=ON \
                 -DENABLE_PYTHON=ON \
                 -DCMAKE_BUILD_TYPE=Debug
        make
        ctest --output-on-failure

    - name: Cleanup build directory
      run: |
        rm -rf build

    - name: Build code and run unit tests with codecov enabled
      run: |
        eval `spack env activate --sh tests`
        mkdir build
        cd build
        cmake .. -DENABLE_COVERAGE=ON \
                 -DENABLE_TESTS=ON \
                 -DENABLE_EXAMPLES=ON \
                 -DENABLE_MPI=ON \
                 -DENABLE_MONA=ON \
                 -DENABLE_SSG=ON \
                 -DENABLE_ABT_IO=ON \
                 -DCMAKE_BUILD_TYPE=Debug
        make
        ctest --output-on-failure

    - name: Send coverage report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
        gcov: true

    - name: Push packages to buildcache and update index
      if: ${{ !cancelled() }}
      run: |
        spack -e tests mirror set --push \
        --oci-username ${{ github.actor }} \
        --oci-password "${{ secrets.GITHUB_TOKEN }}" mochi-buildcache
        spack -e tests buildcache push --base-image ubuntu:22.04 \
        --unsigned --update-index mochi-buildcache
